---
title: "Boxplots for LCHF study"
output: 
  html_notebook: 
    toc: TRUE
    theme: "cosmo"
---
# Repeated measures low carb high fat diet


## Packages
Load the various packages.

```{r setup}

# packages for analysis of repeated measures
library(nlme)
library(car)

# document definition and construction
library(knitr)
opts_knit$set(eval.after = "fig.cap")
library(rmarkdown)

#reading and writing files of various types (in this case, csv and text files)
library(readr)

# data manipulation
library(tidyr)
library(dplyr)
library(tibble)

# pipelining commands
library(magrittr)

# plots
library(ggplot2)

```
## Prepare the data

```{r}
obs <- read_csv("mep_observations.csv")

#sort data by subject
obs <- obs[order(obs$Subject),]

# these models work with factors
obs$Subject <- as.factor(obs$Subject)
obs$TestNumber <- as.factor(obs$TestNumber)
obs <- as_tibble(obs)
obs$Week <- obs$TestNumber
levels(obs$Week) <- c("Baseline", "Week1", "Week2", "Week3")

obs
```




## MEP HR
```{r}
aboxplot <- ggplot(data=obs, aes(x=Week,y=MEPHR)) + 
  geom_boxplot() +
  ylim(120,200) +
  geom_segment(x=1,y=185,xend=2,yend=185) +
  annotate(geom="text", label="p=0.0290", x=1.5, y=188) +
  geom_segment(x=1,y=195,xend=4,yend=195) +
  annotate(geom="text", label="p=0.1769", x=1.5, y=198)

aboxplot

```




## Weight
```{r}
aboxplot <- ggplot(data=obs, aes(x=Week,y=Weight)) + 
  geom_boxplot() +
  ylim(115,180) + 
  geom_segment(x=2,y=167,xend=3,yend=167) +
  annotate(geom="text", label="p=0.0169", x=2.5, y=170) +
  geom_segment(x=1,y=175,xend=4,yend=175) +
  annotate(geom="text", label="p=0.0725", x=2.5, y=178)

aboxplot

```



## MaxRelVO2
```{r}
aboxplot <- ggplot(data=obs, aes(x=Week,y=MaxRelVO2)) + 
  geom_boxplot() + 
  ylim(30,90) + 
  geom_segment(x=3,y=75,xend=4,yend=75) +
  annotate(geom="text", label="p=0.0455", x=3.5, y=78) +
  geom_segment(x=1,y=85,xend=4,yend=85) +
  annotate(geom="text", label="p=0.2305", x=3.5, y=88)

aboxplot
```



## FatBIA
```{r}
aboxplot <- ggplot(data=obs, aes(x=Week,y=FatBIA)) + 
  geom_boxplot() +
  ylim(25,70) +
  geom_segment(x=2,y=60,xend=3,yend=60) +
  annotate(geom="text", label="p=0.0252", x=2.5, y=63) +
  geom_segment(x=1,y=65,xend=4,yend=65) +
  annotate(geom="text", label="p=0.1410", x=2.5, y=68)

aboxplot

```



