---
title: "Diet Analysis Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(tufte)
library(rmarkdown)

library(ggplot2)
library(readxl)
library(gdata)
library(tidyr)
library(dplyr)
library(magrittr)
```
## import data

```{r}
excelfilter <- matrix(c("Excel", "*.xls*"), ncol=2)

diet <- choose.files(filters = excelfilter,
                    caption = "Select diet file",
                    multi=FALSE)  %T>%
        print() %>%
        read_excel(sheet=1)

diet$Subject <- as.factor(diet$Subject)
diet$week <- as.factor(diet$week)
diet$Fatpct <- diet$Fatpct * 100
diet$Carbpct <- diet$Carbpct * 100
diet$Proteinpct <- diet$Proteinpct * 100
diet
```

```{r}
diet_long <- gather(diet, measurement, obs, Fat:kcal)
diet_long %>% 
  subset(measurement %in% c("Carbpct","Fatpct","Proteinpct")) %>%
  ggplot(data=., aes(x=week, y=obs, color=Subject)) + 
    geom_boxplot() + 
    facet_wrap(~measurement, scale="free")
```



## Macronutrient Diet Composition

Diet composition at baseline and during the testing period.  Distribution for each week.

```{r}
ggplot(data=diet, aes(x=week,
                      y=Fatpct,
                      color=Subject)) + 
  geom_boxplot()

```

```{r}
ggplot(data=diet, aes(x=week,
                     y=Carbpct,
                     color=Subject)) + 
  geom_boxplot()

```

```{r}
ggplot(data=diet, aes(x=week,
                     y=Proteinpct,
                     color=Subject)) + 
  geom_boxplot()

```

## Week-to-week diet composition

```{r}
diet %>% 
  group_by(Subject,week) %>%
  summarise_each(funs(sum), Fat, Carb, Protein, kcal)

```

