---
title: "Low Carbohydrate High Fata Data Analysis"
subtitle: "Repeated measures on subjects"
author: "Mark Connolly"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
bibliography: lchf.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
require(ggplot2)
require(readxl)
require(gdata)

# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

# Introduction

The data analysis uses software and packages from The R Project for Statistical Computing[@R-base].

## Data Preparation

```{r}

excelfilter <- matrix(c("Excel", "*.xls*"), ncol=2)

ingestvo2 <- function(afilename) {
  parts <- unlist(strsplit(basename(afilename)," "))
  columns <- data.frame("subj" = as.numeric(parts[1]),
                        "testnumber" = as.numeric(parts[2]),
                        "testdate" = as.Date(parts[3],format="%m%d%y")
                        ) 
  obsvo2 <- read_excel(afilename, sheet=1, skip=4, col_names=FALSE)
  names(obsvo2) <- trim(names(read_excel(afilename, sheet=1, skip=2, col_names=TRUE)))
  obsvo2$interval <- 0:(nrow(obsvo2) - 1)
  return(cbind(columns,obsvo2))
}


list_of_data_frames <- lapply(choose.files(filters = excelfilter,
                                          caption = "Select VO2 files to combine"), 
                              FUN=ingestvo2)

vo2 <- do.call('rbind', list_of_data_frames)

manualmeasures <- read_excel(choose.files(filters = excelfilter,
                               multi = FALSE,
                               caption = "Select the manual measures file"))

vo2data <- merge(vo2, manualmeasures, 
                 by.x=c("subj","testnumber"), 
                 by.y=c("Subject","Test Number"), 
                 all.x=TRUE)

vo2data$subj = as.factor(vo2data$subj)

cursubj <- "123456"

```

## Plotz

```{r fig-12346vo2, fig.cap = "Rel.VO2 ~ Heartrate", cache=TRUE}
ggplot(data=subset(vo2data,subj==cursubj), aes(x=HR, y=Rel.VO2, col=subj)) + 
       geom_point() + 
       geom_smooth() +
       ggtitle(paste("Rel.VO2 ~ Heartrate for subject",cursubj))
```



# References


